services:
  postgres:
    container_name: back-spp
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: 'back-spp'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '123'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass "myStrongPassword"
    volumes:
      - redisdata:/data
    networks:
      - backend

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-ui
    restart: always
    ports:
      - '5540:5540'
    volumes:
      - redisinsight_data:/data
    networks:
      - backend

volumes:
  pgdata:
  redisdata:
  redisinsight_data:

networks:
  backend:
    driver: bridge
