import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

import { Toaster } from 'sonner';

import { cookies } from 'next/headers';
import { ThemeProvider } from 'next-themes';
import AppSidebar from './components/AppSideBar';
import Navbar from './components/Navbar';
import ClientSidebarProvider from './providers/SiderBarProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Fisio Performance',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookiesStore = await cookies();
  const defaultOpen = cookiesStore.get('sidebar_state')?.value === 'true';
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <ClientSidebarProvider>
            <AppSidebar />
            <main className="w-full">
              <Navbar />
              <div className="px-4">{children}</div>
            </main>
          </ClientSidebarProvider>
          <Toaster richColors position="top-right" theme="dark" closeButton />
        </ThemeProvider>
      </body>
    </html>
  );
}
