import { InjuryRecordPageType } from '@/app/types/InjuryRecordPageType';

export const mockInjuryRecords: InjuryRecordPageType[] = [
  {
    id: 1,
    athlete_id: 101,
    athlete_name: 'João Silva',
    position: 'Atacante',
    team: 'Time A',
    injury_type: 'Lesão Muscular',
    severity: 'medium',
    status: 'recovering',
    description: 'Estiramento no quadríceps direito durante treino',
    created_at: '2025-07-20T14:30:00Z',
    recovery_date: '2025-08-05T00:00:00Z',
    days_out: 16,
  },
  {
    id: 2,
    athlete_id: 102,
    athlete_name: 'Maria Santos',
    position: 'Meio-campo',
    team: 'Time A',
    injury_type: 'Entorse',
    severity: 'high',
    status: 'active',
    description: 'Entorse no tornozelo esquerdo',
    created_at: '2025-07-19T09:15:00Z',
    recovery_date: '2025-08-15T00:00:00Z',
    days_out: 27,
  },
  {
    id: 3,
    athlete_id: 103,
    athlete_name: 'Pedro Costa',
    position: 'Zagueiro',
    team: 'Time B',
    injury_type: 'Contusão',
    severity: 'low',
    status: 'recovered',
    description: 'Contusão no joelho direito',
    created_at: '2025-07-15T16:45:00Z',
    recovery_date: '2025-07-22T00:00:00Z',
    days_out: 7,
  },
];
