import { Athlete } from '@/app/types/AthleteType';

export const mockAthletes: Athlete[] = [
  {
    id: 1,
    name: 'Gabriel Faria',
    position: 'Atacante',
    team: 'Time A',
    age: 22,
    height: 175,
    weight: 70,
    riskLevel: 'low',
    vitalSigns: [
      {
        id: 1,
        athlete_id: 1,
        heart_rate: 75,
        vo2_max: 55,
        fatigue_score: 20,
        sleep_quality: 8,
        created_at: '2025-07-22T10:00:00Z',
      },
      {
        id: 2,
        athlete_id: 1,
        heart_rate: 70,
        vo2_max: 56,
        fatigue_score: 15,
        sleep_quality: 9,
        created_at: '2025-07-21T10:00:00Z',
      },
    ],
    injuryRecords: [],
  },
  {
    id: 2,
    name: 'Lucas Pereira',
    position: 'Meio-campo',
    team: 'Time A',
    age: 25,
    height: 180,
    weight: 78,
    riskLevel: 'medium',
    vitalSigns: [
      {
        id: 3,
        athlete_id: 2,
        heart_rate: 85,
        vo2_max: 50,
        fatigue_score: 40,
        sleep_quality: 6,
        created_at: '2025-07-22T11:00:00Z',
      },
    ],
    injuryRecords: [
      {
        id: 1,
        athlete_id: 2,
        injury_type: 'Estiramento',
        body_part: 'Posterior da coxa',
        severity: 'medium',
        status: 'active',
        injury_date: '2025-07-15T00:00:00Z',
        expected_recovery: '2025-08-01T00:00:00Z',
      },
    ],
  },
  {
    id: 3,
    name: 'Ana Rodrigues',
    position: 'Defensor',
    team: 'Time B',
    age: 20,
    height: 168,
    weight: 60,
    riskLevel: 'high',
    vitalSigns: [
      {
        id: 4,
        athlete_id: 3,
        heart_rate: 95,
        vo2_max: 45,
        fatigue_score: 60,
        sleep_quality: 4,
        created_at: '2025-07-22T09:30:00Z',
      },
    ],
    injuryRecords: [
      {
        id: 2,
        athlete_id: 3,
        injury_type: 'Entorse',
        body_part: 'Tornozelo esquerdo',
        severity: 'high',
        status: 'active',
        injury_date: '2025-07-10T00:00:00Z',
        expected_recovery: '2025-08-10T00:00:00Z',
      },
    ],
  },
  {
    id: 4,
    name: 'Carlos Oliveira',
    position: 'Goleiro',
    team: 'Time C',
    age: 28,
    height: 185,
    weight: 85,
    riskLevel: 'low',
    vitalSigns: [
      {
        id: 5,
        athlete_id: 4,
        heart_rate: 68,
        vo2_max: 58,
        fatigue_score: 10,
        sleep_quality: 9,
        created_at: '2025-07-22T10:15:00Z',
      },
    ],
    injuryRecords: [],
  },
  {
    id: 5,
    name: 'Fernanda Lima',
    position: 'Atacante',
    team: 'Time B',
    age: 23,
    height: 170,
    weight: 65,
    riskLevel: 'medium',
    vitalSigns: [
      {
        id: 6,
        athlete_id: 5,
        heart_rate: 80,
        vo2_max: 52,
        fatigue_score: 30,
        sleep_quality: 7,
        created_at: '2025-07-22T10:45:00Z',
      },
    ],
    injuryRecords: [
      {
        id: 3,
        athlete_id: 5,
        injury_type: 'Contusão',
        body_part: 'Ombro direito',
        severity: 'low',
        status: 'recovering',
        injury_date: '2025-07-01T00:00:00Z',
        expected_recovery: '2025-07-25T00:00:00Z',
      },
    ],
  },
];
